include: "rules/common.smk"


if config.get("load_fair_genome_indexer", True):

    include: "rules/fair_genome_indexer_pipeline.smk"


if config.get("load_fair_fastqc_multiqc", True):

    include: "rules/fair_fastqc_multiqc_pipeline.smk"


include: "rules/datavzrd.smk"
include: "rules/fastp.smk"
include: "rules/merge_salmon.smk"
include: "rules/multiqc.smk"
include: "rules/salmon_quant_meta.smk"


rule salmon_quant_target:
    input:
        unpack(get_rnaseq_salmon_quant_target),
    localrule: True
    threads: 1
    resources:
        mem_mb=128,
        runtime=2,
        tmpdir="tmp",
    log:
        "logs/target/salmon_quant_target.log",
    benchmark:
        "logs/target/salmon_quant_target.tsv"
