include: "rules/common.smk"
include: "rules/fastp.smk"

if config.get("load_fair_genome_indexer", True):

    include: "rules/fair_genome_indexer_pipeline.smk"

include: "rules/salmon_quant_meta.smk"
include: "rules/merge_salmon.smk"

rule salmon_quant_target:
    include:
        unpack(get_salmon_quant_target),
    log:
        "logs/target/salmon_quant_target.log"
    benchmark:
        "logs/target/salmon_quant_target.tsv"