# configuration of display in snakemake workflow catalog: https://snakemake.github.io/snakemake-workflow-catalog

usage:
  mandatory-flags:
    desc: Estimate read abundance with Salmon
    flags:
  software-stack-deployment:
    conda: true
    singularity: false
    singularity+conda: true
  report: true
