samples: config/samples.csv

# Optional parameters
params:
  # Optional parameters for pyfaidx
  pyfaidx:
    # Filter-out non canonical chromosomes
    dna: '--regex "^[[0-9]+|X|Y|MT]"'
    # Keep all cdna sequences
    cdna: '--regex "^.+\|.+\|.+\|[[0-9]+|X|Y|MT]"'
  # Optional parameters for agat (filter/correct GTF format)
  agat:
    # Optional parameters for agat_convert_sp_gff2gtf.pl
    gff2gtf: ""
    # Optional parameters for agat_sq_filter_feature_from_fasta.pl
    filter_features: ""
    # Optional parameters for agat_sq_select_feature_by_attribute_value.pl
    select_feature_by_attribute_value: "--attribute 'transcript_support_level' --value '\"NA\"' --test '='"
    # Optional parameters for agat_convert_sp_gff2tsv
    agat_convert_sp_gff2tsv: ""
  # Optional parameters for fastqc
  fastqc: ""
  # Optional parameters for fastp trimming and QC
  fastp:
    # Optional adapter list for fastp trimming
    adapters: ""
    # Optional parameters for fastp command line
    extra: --overrepresentation_analysis --verbose
  salmon:
    # Optional parameters for genome indexation with Salmon
    index: ""
    # Optional parameters for salmon quantification
    # One should always include bootstraping and Bulk RNASeq bias
    quant: --numBootstraps 100 --gcBias --seqBias --posBias
  # Optional parameters for tximport
  tximport: "type='salmon', ignoreTxVersion=TRUE, ignoreAfterBar=TRUE"
  # Optional parameters for multiqc
  multiqc: --module fastqc --module salmon --module fastp --zip-data-dir --verbose --no-megaqc-upload --no-ansi --force

# Optional path to a genome.csv file
genomes: "config/genomes.csv"

# Instenal use only, not described in documentation.
# Deactivate import of fair_genome_indexer pipeline.
# Requires the file `genome.csv` to be filled.
# load_fair_genome_indexer: true
# Deactivate import of fair_fastqc_multiqc pipeline.
# load_fair_fastqc_multiqc: true