$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object


genomes:
  type: string
  description: Path to the CSV file defining genome properties


load_fair_genome_indexer:
  type: boolean
  description: Load (or not) the fair_genome_indexer pipeline


samples:
  type: string
  description: Path to the CSV file defining samples and their corresponding fastq paths

params:
  type: object
  salmon:
    type: object
    description: Optional parameters for Salmon
    index:
      type: string
      description: Optional parameters for salmon index
    quant:
      type: string
      description: Optional parameters for Salmon quant


  fastp:
    type: object
    description: Optional parameters for Fastp
    adapters:
      type: string
      description: Optional adapters to trimm
    extra:
      type: string
      description: Optional command line arguments for Fastp

  type: object
  description: Optional parameters for FastQC, MultiQC, and FastQScreen
  fastqc:
    type: string
    description: Optional parameters for FastQC
  multiqc:
    type: string
    description: Optional parameters for MultiQC
  fastq_screen:
    type: object
    subset:
      type: integer
      description: Number of reads used to build statistics
    fastq_screen_config:
      type: string
      description: Path to fastq screen configuration
    aligner:
      type: string
      description: Aligner used to index references
      pattern: "^bowtie2?"
    required:
      - subset
      - fastq_screen_config
      - aligner
  required:
    - fastqc
    - multiqc
    - fastq_screen
  tximport:
    type: str
    description: Optional parameters for tximport

  fastqc:

required:
  - samples